# Generated by Django 4.2.5 on 2023-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_registration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
