# Generated by Django 4.2.5 on 2023-10-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_alter_registration_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default='nil')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.registration')),
            ],
        ),
    ]
